Use libm to help prevent future terrain generation consistency bugs
Ralith/hypermine pull request #252
Opened 2023-01-03 20:32 UTC by patowen

To prevent requiring the server to send lots of data to the client, terrain generation should be run on both the server and the client separately. To avoid inconsistencies in terrain generation caused by differing implementations of transcendental functions, we use the `libm` library, which provides its own implementation of these functions.

2023-01-03 22:29 UTC, Ralith requested changes
You need to actually replace calls to trancedental functions from std with calls into libm.

2023-01-03 22:32 UTC, patowen commented
Oh yeah. That makes sense in retrospect.

2023-01-03 22:47 UTC, patowen commented
@Ralith: Actually, this seems potentially dangerous. As far as I can tell, there's no way to un-import the std math functions (without something drastic like no_implicit_prelude). Mixing std math and libm math in the codebase seems troublesome to get correct. Do you have a suggestion for how to get libm used reliably?

2023-01-03 22:49 UTC, Ralith commented
LD_PRELOAD something which stubs out the libc versions with ones that call `abort`? Good discipline will be necessary. It's not the end of the world if there's an occasional mistake.

2023-01-03 22:56 UTC, patowen commented
That may work. One other potential concern is that libm's performance may be significantly worse than std's. Since we only need libm for terrain generation, and other things would be self-correcting, we could be leaving performance on the table.

That being said, I'm hopeful that this won't be the bottleneck.

2023-01-03 22:59 UTC, patowen commented
> LD_PRELOAD something which stubs out the libc versions with ones that call `abort`? Good discipline will be necessary. It's not the end of the world if there's an occasional mistake.

Given that it's not the end of the world if there's an occasional mistake, and only worldgen needs consistency, I'm inclined to just not enforce this and instead rely on code reviews to catch human error.

2023-01-03 23:05 UTC, Ralith commented
> One other potential concern is that libm's performance may be significantly worse than std's

This is unlikely; host libc isn't magic.

2023-01-03 23:33 UTC, patowen commented
I believe the main performance benefit of std would be potential hardware implementations of common functions like sqrt. However, I haven't found anything noteworthy during my testing, so I agree that this is nothing to worry about.

I'm noticing that far fewer changes are needed than I originally thought. Anything using `RealField` is affected by nalgebra's `libm-force` feature, so all our generic code uses `libm` without any modifications.

2023-01-04 01:10 UTC, Ralith approved these changes

2023-01-04 01:25 UTC, merged