Allow for number keys to select type of block to be placed
Ralith/hypermine pull request #340
Opened 2024-01-09 05:57 UTC by jhuang97

The ten materials that can be selected can be edited by changing the field material_palette in client/src/sim.rs.

The change in common/src/character_controller/mod.rs was necessary for the server not to crash when running on my machine.

2024-01-09 06:57 UTC, Ralith approved these changes
Thanks, this looks like a nice straightforward improvement!

2024-01-09 06:57 UTC, Ralith commented on common/src/character_controller/mod.rs
> -        up: graph.get_relative_up(position).unwrap(),
This comment isn't meaningful. If there's a bug here, please open a separate PR (or issue) and keep this PR focused.

2024-01-09 06:57 UTC, Ralith commented on client/src/graphics/window.rs
> +                        }
nit: We could avoid listing every key twice by moving this logic into the catch-all `_ => {}` case below, modifying `number_key_to_index` to return `Option`, and calling it there.

2024-01-09 06:57 UTC, Ralith commented on client/src/sim.rs
> +    material_palette: [Material; 10],
nit: this might as well be a `const`, since we're not likely to mutate it any time soon.

2024-01-09 06:57 UTC, Ralith commented on client/src/sim.rs
> +        };
This could be more concise:
```suggestion
        self.selected_material = self.material_palette.get(idx).unwrap_or(self.material_palette[0]);
```

2024-01-09 06:58 UTC, Ralith requested changes

2024-01-10 04:59 UTC, jhuang97 commented
thanks for all the comments! I made changes for all of them and also ran cargo fmt locally.

2024-01-10 08:50 UTC, Ralith approved these changes
Thanks!

2024-01-10 08:50 UTC, merged